=== Connect Admin [[connect_admin]]

As per the architecture, all the StackSaga clients connect to the StackSaga admin server initially (*for submitting the instance metadata*) and as well as during the StackSaga-client is being run (*for submitting the terminated transaction data*).

IF you want to connect your service with the StackSaga admin server, you have to have a *service-account* that has been created by the StackSaga admin.
IF you have a *service-account*, you can provide your service-account username and password for the basic authentication purpose.

NOTE: In the microservice architecture, you will have hundreds of instances running on.
It is enough to have a one service-account for one service-name.
(The `spring.application.name` is considered as the service-name.)

After creating the `service-account`, you will have the basic authentication for the registered service.
Those basic authentication can be provided as follows in the configuration property file:

[source,properties]
----
stacksaga.connect.admin-url=http://localhost:4444
stacksaga.connect.admin-username=order-service
stacksaga.connect.admin-password=*****************
----

NOTE: The default StackSaga-Admin-server running on port *4444*.