Event-store is the location that StackSaga stores the data Relevant to the transaction execution as well as the storing the metadata of the components that you provided like *aggregator details*, *executor details*, *application version details* etc. all the data you can see through the <<stacksaga_admin,StackSaga Admin dashboard>>.
You can configure the database for the event-store as the pattern of database per service.
Otherwise, you can provide one event-store for all services.
But as the best practice, event-store per service is recommended.
You can define a separate schema for event-store by providing the configurations.

. One Event-Store Per Service.
. One Common Event-Store For All Services.

==== One Event-Store Per Service.

image::resources/img/Architecture-Stacksaga-event-store-per-service.drawio.svg[alt="StackSaga Event Store Per Service",height=300]

==== One Common Event-Store For All Services.

image::resources/img/Architecture-Stacksaga-one-event-store-for-all-services.drawio.svg[alt="StackSaga Event Store For All Service",height=300]

