=== Aggregator's Event Casting [[aggregators_event_casting]]

As per the architecture <<version_casting_architecture,documentation>> StackSag does support Aggregator Event <<aggregator_oriented_up_casting,UpCast>> and also Aggregator Event <<aggregator_oriented_down_casting,DownCast>>. +
For the upcasting of the Aggregator Event, there is nothing to be done.
The only thing is adding the new properties.
But the down-casting process is a little more complicated.

To overcome Aggregator's Event down-casting in StackSaga, it can be followed in two different approaches technically.

. Ignore Unknown JSON Properties.
. Collect Missing properties

WARNING: *Ignore Unknown JSON Properties* Is not a recommended approach.
Technically, it is possible to ignore the missing properties in Object Mapper by using `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` globally or using `@JsonIgnoreProperties(ignoreUnknown = true)`.
Annotation in class level.
But it is not recommended in StackSaga.
Because old events have more data that the new one when it provided down-casting changes in your aggregator.
Then, while the old events are processed, that removed data will not be available for accessing.

==== Collect Missing properties [[collect_missing_properties]]

For collecting missing properties it can be used `@JsonAnySetter` and `@JsonAnyGetter` with a custom method.
But you don't need to create all the things from scratch.
Because StackSaga provides the helper class called `MissingJsonPropertyCollector` for extending without writing any custom methods.

NOTE: The root implementation (Custom Aggregator) of the *SagaAggregate* is by default extended from `MissingJsonPropertyCollector`.
Therefore, the root Custom Aggregator class is ready to collect the missing properties.
But if you want to empower other inner classes that are used inside the Root Aggregator class also with Missing properties collector capabilities, you can extend all the inner classes from `MissingJsonPropertyCollector` as well.

Here is an example for down-casting with using `MissingJsonPropertyCollector` implementation.

*Old Version Of the Custom Aggregator.*

[source,java]
----
@Aggregator(
        version = @AggregatorVersion(major = 1, minor = 1, patch = 0),
        idPrefix = "po",
        name = "PlaceOrderAggregator",
        sagaSerializable = PlaceOrderAggregatorSample.class,
        mapper = PlaceOrderAggregatorJsonMapper.class
)
@Getter
@Setter
public class PlaceOrderAggregator extends SagaAggregate {

    public PlaceOrderAggregator() {
        super(PlaceOrderAggregator.class);
    }

    @JsonProperty("order_id")
    private String orderId;

    @JsonProperty("username")
    private String username;

    @JsonProperty("total")
    private Double total;

    @JsonProperty("is_active")
    private Integer isActive;

    @JsonProperty("comment")
    private String comment;

    @JsonProperty("item_details")
    private List<ItemDetail> itemDetails = new ArrayList<>();

    @Getter
    @Setter
    @AllArgsConstructor
    @NoArgsConstructor
    public static class ItemDetail implements Serializable {

        @JsonProperty("order_id")
        private String itemName;

        @JsonProperty("qty")
        private int qty;

        @JsonProperty("price")
        private double price;

        @JsonProperty("note")
        private String note;
    }
}
----

*New Version Of the Custom Aggregator.*

[source,java]
----
@Aggregator(
        version = @AggregatorVersion(major = 1, minor = 1, patch = 1),
        idPrefix = "po",
        name = "PlaceOrderAggregator",
        sagaSerializable = PlaceOrderAggregatorSample.class,
        mapper = PlaceOrderAggregatorJsonMapper.class
)
@Getter
@Setter
public class PlaceOrderAggregator extends SagaAggregate {

    public PlaceOrderAggregator() {
        super(PlaceOrderAggregator.class);
    }

    @JsonProperty("order_id")
    private String orderId;

    @JsonProperty("username")
    private String username;

    @JsonProperty("total")
    private Double total;

    @JsonProperty("is_active")
    private Integer isActive;

    //@JsonProperty("is_active") //<1>
    //private String comment;

    @JsonProperty("item_details")
    private List<ItemDetail> itemDetails = new ArrayList<>();

    @Getter
    @Setter
    @AllArgsConstructor
    @NoArgsConstructor
    public static class ItemDetail extends MissingJsonPropertyCollector { //<2>

        @JsonProperty("order_id")
        private String itemName;

        @JsonProperty("qty")
        private int qty;

        @JsonProperty("price")
        private double price;

        //@JsonProperty("note") //<3>
        //private String note;
    }
}
----

*Getting The Collected Properties For specific Version.*

[source,java]
----
@SagaExecutor(executeFor = "order-service", liveCheck = true, value = "OrderSaveExecutor")
@AllArgsConstructor
public class OrderSaveExecutor implements CommandExecutor<PlaceOrderAggregator> {

    @Override
    public ProcessStepManager<PlaceOrderAggregator> doProcess(
            ProcessStack processStack,
            PlaceOrderAggregator aggregator,
            ProcessStepManagerUtil<PlaceOrderAggregator> stepManager
    ) throws RetryableExecutorException, NonRetryableExecutorException {

        if (aggregator.getRealVersionAsString().equals("1.0.0")) { //<1>
            String comment = aggregator.getMissingProperties().get("comment").toString(); //<2>
            System.out.println("comment = " + comment);

            for (PlaceOrderAggregator.ItemDetail itemDetail : aggregator.getItemDetails()) { //<3>
                String note = itemDetail.getMissingProperties().get("note").toString(); //<3>
                System.out.println("note = " + note);
            }
        }
        ...

        return stepManager.next(UpdateStockExecutor.class);
    }

    @Override
    public void doRevert(
            ProcessStack processStack,
            NonRetryableExecutorException e,
            PlaceOrderAggregator aggregator,
            RevertHintStore revertHintStore
    ) throws RetryableExecutorException {
        ...
    }
}
----